kind: Deployment
apiVersion: apps/v1
metadata:
  name: delivery-service-{{ .Values.versionName }}
  labels:
    app: delivery-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
        version: {{ .Values.version }}
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: delivery-service
          image: quay.io/jamjones/courie-delivery:{{ default "latest" .Values.dockerTag }}
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: delivery-service
          imagePullPolicy: Always
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%