{{- if .Values.firstInstall -}}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: delivery-service-dr
spec:
  host: delivery-service
  subsets:
  - name: {{ .Values.versionName }}
    labels:
      version: {{ .Values.version }}
{{- end }}