{{- if .Values.firstInstall -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: delivery-service-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "delivery-api.{{ .Values.baseOpenshiftAppHostname }}"
{{- end }}