{{- if .Values.firstInstall -}}
kind: Service
apiVersion: v1
metadata:
  name: delivery-service
  labels:
    app: delivery-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: delivery-service
  type: ClusterIP
{{- end }}